#cloud-config
users:
  - default
  - name: prometheus
    shell: /bin/false
  - name: node_exporter
    shell: /bin/false
  - name: minecraft-exporter
    shell: /bin/false

package_update: true

packages:
  - apt-transport-https
  - curl
  - fail2ban
  - openjdk-17-jre-headless
  - ca-certificates

write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

  - path: /tmp/server.properties
    content: |
      level-seed=stackitminecraftrocks
      view-distance=10
      enable-jmx-monitoring=false
      server-ip=
      resource-pack-prompt=
      gamemode=survival
      allow-nether=true
      enable-command-block=false
      sync-chunk-writes=true
      enable-query=false
      op-permission-level=4
      prevent-proxy-connections=false
      resource-pack=
      node-broadcast-range-percentage=100
      level-name=world
      player-idle-timeout=0
      motd=\u00A7bAzure \u00A7rMinecraft --- \u00A76PaperMC \u00A7redition
      query.port=25565
      force-gamemode=false
      rate-limit=0
      hardcore=false
      white-list=false
      broadcast-console-to-ops=true
      pvp=true
      spawn-npcs=true
      spawn-animals=true
      snooper-enabled=true
      difficulty=easy
      function-permission-level=2
      network-compression-threshold=256
      text-filtering-config=
      require-resource-pack=false
      spawn-monsters=true
      max-tick-time=60000
      enforce-whitelist=false
      use-native-transport=true
      max-players=100
      resource-pack-sha1=
      spawn-protection=16
      online-mode=true
      enable-status=true
      allow-flight=false
      max-world-size=
      broadcast-rcon-to-ops=true
      rcon.port=25575
      enable-rcon=true
      rcon.password=test
      server-port=25565

  - path: /tmp/prometheus.yml
    content: |
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: 'prometheus'
          scrape_interval: 5s
          static_configs:
            - targets: ['localhost:9090']
        - job_name: 'node_exporter'
          scrape_interval: 5s
          static_configs:
            - targets: ['localhost:9100']
        - job_name: 'minecraft_exporter'
          scrape_interval: 1m
          static_configs:
            - targets: ['localhost:9150']

  - path: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target
      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
          --config.file /etc/prometheus/prometheus.yml \
          --storage.tsdb.path /var/lib/prometheus/ \
          --web.console.templates=/etc/prometheus/consoles \
          --web.console.libraries=/etc/prometheus/console_libraries
      [Install]
      WantedBy=multi-user.target

  - path: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target
      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter
      [Install]
      WantedBy=multi-user.target

  - path: /etc/systemd/system/minecraft-exporter.service
    content: |
      [Unit]
      Description=Minecraft Exporter
      Wants=network-online.target
      After=network-online.target
      [Service]
      User=minecraft_exporter
      Group=minecraft_exporter
      Type=simple
      ExecStart=/usr/local/bin/minecraft-exporter \
          --mc.rcon-password=test
      [Install]
      WantedBy=multi-user.target

  - path: /etc/systemd/system/quilt.service
    content: |
      [Unit]
      Description=The Quilt Project
      Documentation=https://quiltmc.org/
      DefaultDependencies=no
      After=network.target
      [Service]
      WorkingDirectory=/quilt
      Type=simple
      ExecStart=/usr/bin/java -Xmx4G -Xms4G -jar server.jar nogui
      Restart=on-failure
      RestartSec=5
      [Install]
      WantedBy=multi-user.target

  - path: /etc/fail2ban/jail.local
    content: |
      [sshd]
      port = 22
      enabled = true
      maxretry = 3
      bantime = 1000
      ignoreip = 

  - path: /run/cloud-init.bash
    content: |
      set -Cefuxo pipefail

      architecture=$(dpkg --print-architecture)

      etc=/etc
      lib=/var/lib
      local=/usr/local
      bin=$local/bin
      src=$local/src

      set_archive() {
        local name=$1 version=$2 owner=$3 repo=$4 delim=${5--}

        archive=$name$delim$version.linux-$architecture

        local url=https://github.com/$owner/$repo/releases/download/v$version/$archive.tar.gz

        if [ $mkdir = yes ]; then
          local src=$src/$archive
          mkdir -p $archive
        fi

        curl -LSfs $url | tar xz -C $src
      }

      make_dirs() {
        local user=$1 group=$2

        for dir in ${dirs[@]}; do
          mkdir $dir
          chown $user:$group $dir
        done
      }

      download_quilt_release() {
        url=https://maven.quiltmc.org/repository/release/org/quiltmc/$name/latest/quilt-installer-latest.jar

        curl -sLSf $url > /quilt/server.jar
        echo "eula=true" > /minecraft/eula.txt
        mv /tmp/server.properties /minecraft/server.properties
        chmod a+rwx /minecraft

      }

      install_nodes() {
        for node in ${nodes[@]}
        do
          cp -r $src/${release[name]}/$node $dir
          chown -R ${unit[owner]}:${unit[group]} $dir/$node
        done
      }


      handle_unit() {
        systemctl daemon-reload
        systemctl start $1
        systemctl enable $1
      }

      configure_iptables() {
        iptables -I INPUT -j ACCEPT

        # iptables -A INPUT -p tcp -m state --state NEW --dport 25555 -j ACCEPT
        # iptables-save
        # dpkg-reconfigure iptables-persistent

        # iptables -P INPUT DROP
        # iptables -P OUTPUT DROP
        # iptables -P FORWARD DROP
      }

      declare -A unit=(
        [user]=$name
        [group]=$name
        [name]=$name
      )

      archive=
      set_archive prometheus 2.36.1 prometheus prometheus

      declare -A dirs=(
        [etc]=/etc/prometheus
        [lib]=/var/lib/prometheus
      )
      make_dirs

      nodes=(
        prometheus
        promtool
      )
      dir=$bin
      install_from_source
      
      nodes=(
        consoles
        console_libraries
        prometheus.yml
      )
      dir=${dirs[etc]}
      install_from_source

      handle_unit

      declare -A release=(
        [owner]=prometheus
        [repo]=node_exporter
        [version]=1.3.1
      )
      download_release

      declare -A unit=(
        [owner]=$name
        [group]=$name
        [name]=$name
      )
      declare -a programs=($name)

      download_github_release
      nodes=${programs[@]} dir=$bin install_from_source
      name=${unit[name]} handle_unit


       version=${versions[$name]}

      declare -A release=([owner]=dirien [repo]=minecraft-prometheus-exporter [version]=$version)
      declare -A unit=([owner]=$name [group]=$name [name]=$name)
      declare -a programs=($name)

      mkdir=yes delim=_ download_github_release
      nodes=${programs[@]} dir=$bin install_from_source
      name=${unit[name]} handle_unit


      name=quilt-installer version=${versions[$name]} 

      declare -A release=(
        [name]=quilt-installer
        [owner]=quiltmc
        [repo]=quilt-installer
        [version]=latest
      )
      declare -A unit=([owner]=quiltmc [name]=$name)
      delcare dirs=(/quilt)

      make_dirs
      download_quilt_release
      handle_unit
      

      sed -i 's/#Port 22/Port 22/g' /etc/ssh/sshd_config
      service sshd restart


      systemctl restart fail2ban

runcmd:
  - [ /bin/bash, /run/cloud-init.bash ]
