on: workflow_dispatch
name: Azure ARM
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: make user-data

    - uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: bicep/main.bicep
        parameters: >
          user=${{ secrets.BICEP_USER }}
          servicePrincipal=${{ secrets.BICEP_SERVICE_PRINCIPAL }}
          publicKey="${{ secrets.SSH_PUBLIC_KEY }}"
          privateKey="${{ secrets.SSH_PRIVATE_KEY }}"
        failOnStdErr: false
